// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTrackerCost = "tracker_cost"

// TrackerCost mapped from table <tracker_cost>
type TrackerCost struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	TrackerType   string    `gorm:"column:tracker_type;not null" json:"tracker_type"`
	TrackerID     int64     `gorm:"column:tracker_id;not null" json:"tracker_id"`
	PDate         string    `gorm:"column:p_date;not null" json:"p_date"`
	TotalCost7Day int64     `gorm:"column:total_cost_7day;not null" json:"total_cost_7day"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP(1)" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP(1)" json:"updated_at"`
}

// TableName TrackerCost's table name
func (*TrackerCost) TableName() string {
	return TableNameTrackerCost
}
