// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebTrackerUserRelation = "web_tracker_user_relation"

// WebTrackerUserRelation Tracker and user relation table
type WebTrackerUserRelation struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Auto-increment primary key" json:"id"`                   // Auto-increment primary key
	TrackerID  int64     `gorm:"column:tracker_id;not null;comment:Tracker ID" json:"tracker_id"`                                        // Tracker ID
	UserID     int64     `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`                                                 // User ID
	CreateDate time.Time `gorm:"column:create_date;not null;default:CURRENT_TIMESTAMP(1);comment:Creation timestamp" json:"create_date"` // Creation timestamp
}

// TableName WebTrackerUserRelation's table name
func (*WebTrackerUserRelation) TableName() string {
	return TableNameWebTrackerUserRelation
}
