// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	TrackerCost            *trackerCost
	WebTracker             *webTracker
	WebTrackerUserRelation *webTrackerUserRelation
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TrackerCost = &Q.TrackerCost
	WebTracker = &Q.WebTracker
	WebTrackerUserRelation = &Q.WebTrackerUserRelation
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		TrackerCost:            newTrackerCost(db, opts...),
		WebTracker:             newWebTracker(db, opts...),
		WebTrackerUserRelation: newWebTrackerUserRelation(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TrackerCost            trackerCost
	WebTracker             webTracker
	WebTrackerUserRelation webTrackerUserRelation
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		TrackerCost:            q.TrackerCost.clone(db),
		WebTracker:             q.WebTracker.clone(db),
		WebTrackerUserRelation: q.WebTrackerUserRelation.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		TrackerCost:            q.TrackerCost.replaceDB(db),
		WebTracker:             q.WebTracker.replaceDB(db),
		WebTrackerUserRelation: q.WebTrackerUserRelation.replaceDB(db),
	}
}

type queryCtx struct {
	TrackerCost            ITrackerCostDo
	WebTracker             IWebTrackerDo
	WebTrackerUserRelation IWebTrackerUserRelationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TrackerCost:            q.TrackerCost.WithContext(ctx),
		WebTracker:             q.WebTracker.WithContext(ctx),
		WebTrackerUserRelation: q.WebTrackerUserRelation.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
