// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                              = new(Query)
	AnalyticsDataSourceCost        *analyticsDataSourceCost
	AnalyticsMsg                   *analyticsMsg
	AnalyticsWeb                   *analyticsWeb
	AnalyticsWebAdvertiserRelation *analyticsWebAdvertiserRelation
	User                           *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AnalyticsDataSourceCost = &Q.AnalyticsDataSourceCost
	AnalyticsMsg = &Q.AnalyticsMsg
	AnalyticsWeb = &Q.AnalyticsWeb
	AnalyticsWebAdvertiserRelation = &Q.AnalyticsWebAdvertiserRelation
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                             db,
		AnalyticsDataSourceCost:        newAnalyticsDataSourceCost(db, opts...),
		AnalyticsMsg:                   newAnalyticsMsg(db, opts...),
		AnalyticsWeb:                   newAnalyticsWeb(db, opts...),
		AnalyticsWebAdvertiserRelation: newAnalyticsWebAdvertiserRelation(db, opts...),
		User:                           newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AnalyticsDataSourceCost        analyticsDataSourceCost
	AnalyticsMsg                   analyticsMsg
	AnalyticsWeb                   analyticsWeb
	AnalyticsWebAdvertiserRelation analyticsWebAdvertiserRelation
	User                           user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                             db,
		AnalyticsDataSourceCost:        q.AnalyticsDataSourceCost.clone(db),
		AnalyticsMsg:                   q.AnalyticsMsg.clone(db),
		AnalyticsWeb:                   q.AnalyticsWeb.clone(db),
		AnalyticsWebAdvertiserRelation: q.AnalyticsWebAdvertiserRelation.clone(db),
		User:                           q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                             db,
		AnalyticsDataSourceCost:        q.AnalyticsDataSourceCost.replaceDB(db),
		AnalyticsMsg:                   q.AnalyticsMsg.replaceDB(db),
		AnalyticsWeb:                   q.AnalyticsWeb.replaceDB(db),
		AnalyticsWebAdvertiserRelation: q.AnalyticsWebAdvertiserRelation.replaceDB(db),
		User:                           q.User.replaceDB(db),
	}
}

type queryCtx struct {
	AnalyticsDataSourceCost        IAnalyticsDataSourceCostDo
	AnalyticsMsg                   IAnalyticsMsgDo
	AnalyticsWeb                   IAnalyticsWebDo
	AnalyticsWebAdvertiserRelation IAnalyticsWebAdvertiserRelationDo
	User                           IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AnalyticsDataSourceCost:        q.AnalyticsDataSourceCost.WithContext(ctx),
		AnalyticsMsg:                   q.AnalyticsMsg.WithContext(ctx),
		AnalyticsWeb:                   q.AnalyticsWeb.WithContext(ctx),
		AnalyticsWebAdvertiserRelation: q.AnalyticsWebAdvertiserRelation.WithContext(ctx),
		User:                           q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
