// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAnalyticsMsg = "analytics_msg"

// AnalyticsMsg mapped from table <analytics_msg>
type AnalyticsMsg struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdvID     int64          `gorm:"column:adv_id;not null" json:"adv_id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(1)" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName AnalyticsMsg's table name
func (*AnalyticsMsg) TableName() string {
	return TableNameAnalyticsMsg
}
