// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAnalyticsWebAdvertiserRelation = "analytics_web_advertiser_relation"

// AnalyticsWebAdvertiserRelation mapped from table <analytics_web_advertiser_relation>
type AnalyticsWebAdvertiserRelation struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WebID      int64     `gorm:"column:web_id;not null" json:"web_id"`
	AdvID      int64     `gorm:"column:adv_id;not null" json:"adv_id"`
	CreateDate time.Time `gorm:"column:create_date;not null;default:CURRENT_TIMESTAMP(1)" json:"create_date"`
}

// TableName AnalyticsWebAdvertiserRelation's table name
func (*AnalyticsWebAdvertiserRelation) TableName() string {
	return TableNameAnalyticsWebAdvertiserRelation
}
