// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAnalyticsWeb = "analytics_web"

// AnalyticsWeb mapped from table <analytics_web>
type AnalyticsWeb struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WebCode        string         `gorm:"column:web_code;not null" json:"web_code"`
	Name           string         `gorm:"column:name;not null" json:"name"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(1)" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Version        int32          `gorm:"column:version;not null" json:"version"`
	Extra          string         `gorm:"column:extra;not null;default:{}" json:"extra"`
	EventSetupMode int32          `gorm:"column:event_setup_mode;not null" json:"event_setup_mode"`
}

// TableName AnalyticsWeb's table name
func (*AnalyticsWeb) TableName() string {
	return TableNameAnalyticsWeb
}
