// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAnalyticsDataSourceCost = "analytics_data_source_cost"

// AnalyticsDataSourceCost mapped from table <analytics_data_source_cost>
type AnalyticsDataSourceCost struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdvID         int64     `gorm:"column:adv_id;not null" json:"adv_id"`
	SourceType    string    `gorm:"column:source_type;not null" json:"source_type"`
	SourceID      int64     `gorm:"column:source_id;not null" json:"source_id"`
	TotalCost7day int64     `gorm:"column:total_cost_7day;not null" json:"total_cost_7day"`
	PDate         string    `gorm:"column:p_date;not null" json:"p_date"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AnalyticsDataSourceCost's table name
func (*AnalyticsDataSourceCost) TableName() string {
	return TableNameAnalyticsDataSourceCost
}
